spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/czy_12_13?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

mybatis:
  # 指定mapper.xml的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰转换
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.mybatisdemo.mapper: debug
